//
//  FirstInteractor.swift
//  ColorPop
//
//  Created by Raymond Law on 3/20/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstBusinessLogic
{
  func doSomething(request: First.Something.Request)
}

protocol FirstDataStore
{
  //var name: String { get set }
}

class FirstInteractor: FirstBusinessLogic, FirstDataStore
{
  var presenter: FirstPresentationLogic?
  var worker: FirstWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: First.Something.Request)
  {
    worker = FirstWorker()
    worker?.doSomeWork()
    
    let response = First.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
