//
//  ColorRouter.swift
//  ColorPop
//
//  Created by Raymond Law on 3/20/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ColorRoutingLogic
{
  func routeToSecond(segue: UIStoryboardSegue?)
}

protocol ColorDataPassing
{
  var dataStore: ColorDataStore? { get }
}

class ColorRouter: NSObject, ColorRoutingLogic, ColorDataPassing
{
  weak var viewController: ColorViewController?
  var dataStore: ColorDataStore?
  
  // MARK: Routing
  
  func routeToSecond(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! SecondViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSecond(source: dataStore!, destination: &destinationDS)
    } else {
      let navigationController = viewController?.presentingViewController as? UINavigationController
      let destinationVC = navigationController?.topViewController as! SecondViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSecond(source: dataStore!, destination: &destinationDS)
      navigateToSecond(source: viewController!, destination: destinationVC)
    }
  }
  
  // MARK: Navigation
  
  func navigateToSecond(source: ColorViewController, destination: SecondViewController)
  {
    destination.dismiss(animated: true, completion: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSecond(source: ColorDataStore, destination: inout SecondDataStore)
  {
    destination.backgroundColor = source.selectedColor
  }
}
