//
//  SecondModels.swift
//  ColorPop
//
//  Created by Raymond Law on 3/20/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Second
{
  // MARK: Use cases
  
  enum ChangeBackgroundColor
  {
    struct Request
    {
    }
    struct Response
    {
      var color: UIColor
    }
    struct ViewModel
    {
      var color: UIColor
    }
  }
}
