//
//  SecondViewController.swift
//  ColorPop
//
//  Created by Raymond Law on 3/20/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondDisplayLogic: class
{
  func displayBackgroundColor(viewModel: Second.ChangeBackgroundColor.ViewModel)
}

class SecondViewController: UIViewController, SecondDisplayLogic
{
  var interactor: SecondBusinessLogic?
  var router: (NSObjectProtocol & SecondRoutingLogic & SecondDataPassing)?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SecondInteractor()
    let presenter = SecondPresenter()
    let router = SecondRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
  }
  
  // MARK: Change background color
  
  func changeBackgroundColor()
  {
    let request = Second.ChangeBackgroundColor.Request()
    interactor?.changeBackgroundColor(request: request)
  }
  
  func displayBackgroundColor(viewModel: Second.ChangeBackgroundColor.ViewModel)
  {
    view.backgroundColor = viewModel.color
  }
}
