//
//  SecondInteractor.swift
//  ColorPop
//
//  Created by Raymond Law on 3/20/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondBusinessLogic
{
  func changeBackgroundColor(request: Second.ChangeBackgroundColor.Request)
}

protocol SecondDataStore
{
  var backgroundColor: UIColor? { get set }
}

class SecondInteractor: SecondBusinessLogic, SecondDataStore
{
  var presenter: SecondPresentationLogic?
  var backgroundColor: UIColor? {
    didSet
    {
      let request = Second.ChangeBackgroundColor.Request()
      changeBackgroundColor(request: request)
    }
  }
  
  // MARK: Change background color
  
  func changeBackgroundColor(request: Second.ChangeBackgroundColor.Request)
  {
    if let backgroundColor = backgroundColor {
      let response = Second.ChangeBackgroundColor.Response(color: backgroundColor)
      presenter?.presentBackgroundColor(response: response)
    }
  }
}
